# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-scf027QMNOu3R69_CwTgNs5ikj7YtY
"""

import pandas as pd
import matplotlib.pyplot as plt
csv_file_path = '/content/drive/MyDrive/API_SP.POP.TOTL_DS2_en_csv_v2_242541.zip (Unzipped Files)/Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_242541.csv'
data = pd.read_csv(csv_file_path)

print(data.head())

print(data.tail())

print(data.info())

print(data.columns)

print(data.describe())

category_column = 'Region'
category_counts = data[category_column].value_counts()
category_counts.plot(kind='bar', color='skyblue')
plt.xlabel(category_column)
plt.ylabel('Count')
plt.title(f'Distribution of {category_column}')
plt.show()

data.isnull().sum()